### ISSUE TITLE
Pytorch: DLL load failed: The operating system cannot run %1

### ISSUE THREAD

**Issue by upinthewoodsdownonmymind** [as-ideas/ForwardTacotron#23]
hello.
as the title says, i am experiencing this problem when i preprocess the ljspeech dataset.

``python preprocess.py --path /dataset_folder/
Traceback (most recent call last):
  File "preprocess.py", line 4, in <module>
    from utils.display import *
  File "F:\Downloads\ForwardTacotron-master\ForwardTacotron-master\utils\__init__.py", line 6, in <module>
    import torch
  File "C:\Users\****\Miniconda3\envs\tacotron\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: The operating system cannot run %1.
``
can someone help? thanks

**Comment by cschaefer26** [comment]
Hi, this seems to be a version problem with pytorch and some other library. Did you try to switch to another pytorch version?
