### ISSUE TITLE
Valueerror not enough values to unpack (expected 2 got 0)

### ISSUE THREAD

**Issue by Xlikes** [as-ideas/ForwardTacotron#66]
I am new to TTS and have also worked very little with Phyton on Windows.

I get the following error with the python train_tacotron.py command:

Traceback (most recent call last):
  File "C:\Users\PC\Desktop\ForwardTacotron-master\train_tacotron.py", line 192, in <module>
    trainer.train(model, optimizer)
  File "C:\Users\PC\Desktop\ForwardTacotron-master\trainer\taco_trainer.py", line 42, in train
    train_set, val_set = get_tts_datasets(
  File "C:\Users\PC\Desktop\ForwardTacotron-master\utils\dataset.py", line 166, in get_tts_datasets
    train_ids, train_lens = zip(*train_data)
ValueError: not enough values to unpack (expected 2, got 0)

With the files from LJSpeech this error does not come.
Now the question is where is the error?
The order structure should not be the problem
-wav
--0001
--....
--0021
-metadata.csv

As a test I have only 21 files/entries are these just too few?

**Comment by cschaefer26** [comment]
Hi, looks like the train set is empty, probably because with 21 files everything lands in the validation set (standard config for n_val=200). 21 files is surely not enough to really do anything to be honest, you would need at least 500 or so.

**Comment by Xlikes** [comment]
So it's not possible to get a halfway usable result with so few files? I was hoping I could teach the voice and then create/teach more files with the generated voice.

The 21 voices are spoken texts of a speaker from a game. The goal was to reproduce the voice as good as possible and to dub some dialogs.
